### ISSUE TITLE
Feature Request: Add support for 1.8.8

### ISSUE THREAD

**Issue by WaveBleak** [SkytAsul/GuardianBeam#24]
Hey, I would really appreciate if you at least try to add support for 1.8.8. I have tried to backport the API myself but I could never get it to work. I know there's probably a reason for you not having it work with 1.8.8, but I know it must be possible since there's the other people who have done it (although in a bit of a rough and glitchy way)

The reason it means so much to me is because there's only 1 API I know of that does this in 1.8.8 and that API is laggy, choppy and glitchy and the plugin I'm developing is heavily reliant on the guardian beams.

Edit: Btw I do completely realize the End Crystals Beams wouldn't work in 1.8.8, I only want the Guardian Beams :D

**Comment by SkytAsul** [comment]
Hello, I have not added 1.8 support and I will not for the simple reason that the NMS structure (especially the one related to entity network data) has drastically changed between 1.8 and 1.9. It would require a lot of changes in my API, and it would make the code a lot less readable (and it is already quite difficult to grasp). Not to mention 1.8 is more than 8 years old and I simply do not want to spend hours on such an old version.
Though, if you want to use it in 1.8 specifically, you could make your own API. It would not require reflection because you are targeting 1 single version, so it should be easier than mine.
